name: 'Analyse Microsoft 365 compliance results'
description: 'Github Action to analyse Microsoft 365 app compliance results'
inputs:
  report-name:
    description: 'name of the compliance report'
    required: true
  deployment-name:
    description: 'deployment name'
    required: true
  tenant-id:
    description: 'tenant'
    required: true
  subscription-id:
    description: 'subscription'
    required: true
  resource-group:
    description: 'resource-group'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'